defaults: &defaults
  app:
    name: 'Mint'
    slogan: 'Mint is not terminal'
    copy_right: '&copy; 2014 TPC All Rights Reserved.'
  time:
    working_hours:
      am:
        from: 9
        to: 12
      pm:
        from: 13
        to: 18

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
